# Create a docker compose to dev node js application and mongodb

version: '3.1'

services:
  node:
    container_name: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    env_file: .env
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    env_file: .env
