@baseUrl = http://localhost
@port = 3333
@host = {{baseUrl}}:{{port}}
@defaultAuthor = 64e29abe2903061ce2cd14ab

### Get
GET {{host}}/

### Get books
GET {{host}}/books

### Get book
GET {{host}}/books/64dd78b03ed003b96cd2f5ce

### Post book
POST {{host}}/books
content-type: application/json

{
  "title": "Harry Potter {{$randomInt 0 99}}",
  "author": "J. 12K. Rowling",
  "publisher": "Rowling",
  "numberOfPages": {{$randomInt 150 500}}
}

### Update book
PUT {{host}}/books/64e0c7b54f3792b2ddb09635
content-type: application/json

{
  "author": "{{defaultAuthor}}"
}

### Delete book
DELETE {{host}}/books/64e0e489fddf725ca49ed72a

### Get authors
GET {{host}}/authors

### Get author
GET {{host}}/authors/64e29abe2903061ce2cd14ab

### Post author
POST {{host}}/authors
content-type: application/json

{
  "name": "Rowling",
  "nationality":"BR"
}

### Update author
PUT {{host}}/authors/64e0e52f7e34a2b3dcdb3afe
content-type: application/json

{
  "name": "Rowling",
  "nationality":"BR"
}

### Delete book
DELETE {{host}}/authors/64e29ac22903061ce2cd14ad